---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: "https://github.com/codespell-project/codespell"
    rev: v2.0.0
    hooks:
      - id: codespell

  - repo: local
    hooks:
      - id: zabbix-template
        name: Zabbix template
        description: Check that the Zabbix template file up to date
        entry: build.sh
        language: script
        pass_filenames: false
        always_run: true
